image: "hub.ricebook.net/base/centos:onbuild-eru-core-2017.07.26"
rpm:
  script:
    - "cp -r $CI_PROJECT_DIR $GOPATH/src/gitlab.ricebook.net/platform/"
    - "cd $GOPATH/src/gitlab.ricebook.net/platform/lambda"
    - "make build"
    - "echo 'start make rpm'"
    - "./make-rpm"
    - "echo 'make rpm done'"
    - "cp eru-lambda*.rpm $CI_PROJECT_DIR"
  artifacts:
    paths:
      - "eru-lambda*.rpm"
    expire_in: 1 week
