image: "hub.ricebook.net/base/centos:onbuild-eru-core-2017.07.26"
stages:
  - test
  - build
  - rpm
test:
  stage: test
  script:
    - "cp -r $CI_PROJECT_DIR $GOPATH/src/gitlab.ricebook.net/platform/"
    - "cd $GOPATH/src/gitlab.ricebook.net/platform/lambda"
    - make test
build:
  stage: build
  script:
    - "cp -r $CI_PROJECT_DIR $GOPATH/src/gitlab.ricebook.net/platform/"
    - "cd $GOPATH/src/gitlab.ricebook.net/platform/lambda"
    - make build
    - cp -r lambda $CI_PROJECT_DIR
  artifacts:
    paths:
      - "lambda"
    expire_in: 1 week
rpm:
  stage: rpm
  script:
    - make rpm
  artifacts:
    paths:
      - "eru-lambda*.rpm"
    expire_in: 1 week
